#!/bin/sh

if ! command -v docker ; then
  echo 'Need the docker command. Please install packages to provide it' 1>&2
  exit 1
fi

set -ev

docker run --rm -it --name jenkins_docker --privileged -p 8080:8080 -v $PWD/certs/:/certs/:rw -v $PWD/var-lib-docker/:/var/lib/docker/:rw -v $PWD/jenkins_home/:/var/jenkins_home/:rw --cpuset-cpus=1,3,5,7 --cpu-period=10000 local/docker-jenkins-alpine

